@startuml
'https://plantuml.com/sequence-diagram

title OS update
autonumber
actor User

User -> "EdgeDevice CR": Update with new target version
Operator -> "EdgeDevice CR": Process
Operator -> "HTTP server": Upload new OS version
Device -> Device: Automatic OS update and restart
Agent -> Operator: Heartbeat with new OS version
Operator -> "EdgeDevice CR": Update status with new installed version

@enduml