apiVersion: v1
kind: Secret
metadata:
  name: cloudcore
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
stringData:
  rootCA.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFmTCCA4GgAwIBAgIUXq/PGFjiH9h5aMF/5i4CvogVoIIwDQYJKoZIhvcNAQEL
    BQAwXDELMAkGA1UEBhMCQ04xETAPBgNVBAgMCFpoZWppYW5nMREwDwYDVQQHDAhI
    YW5nemhvdTERMA8GA1UECgwIS3ViZUVkZ2UxFDASBgNVBAMMC2t1YmVlZGdlLmlv
    MB4XDTIxMDYxODE0MzgwOFoXDTMxMDYxNjE0MzgwOFowXDELMAkGA1UEBhMCQ04x
    ETAPBgNVBAgMCFpoZWppYW5nMREwDwYDVQQHDAhIYW5nemhvdTERMA8GA1UECgwI
    S3ViZUVkZ2UxFDASBgNVBAMMC2t1YmVlZGdlLmlvMIICIjANBgkqhkiG9w0BAQEF
    AAOCAg8AMIICCgKCAgEA53mpQmGInDSHpohhUS9g9fGpaesaXUKw5pdApCvXxnZJ
    JKdbz1EP+R+y0j3PrZbkUgBla/kdZpPjfYK9QYBhtFlaMeGvSe0F+9FF+GThXcFI
    xJxTJvRVWdDnw6EuyH/8xzlXiGYHE43e6DhLJdhvKAZiadr7D/yinNzR+9DkqQ8U
    4CrcA3D6UCmleix12bBQL5JmFaZ7/LqygNjgk3ENojit9AM4XSeHqpfLQLeCiqYT
    S/GgATy2aovhcX566leOobdfxn1bp/BIqSSsY1FvydyTJFeKjnjftrJqVI1jvUCo
    8kZwjofyyaFdyu7NNkGZKhrZBt+6FMU/ezwFhJAuxgShkvmqQ+GAwNp0Y0+EYB/j
    gsE3okgVaYjoDZEcS/vaJ7Zd1jzC5A7FCkWlPsQvsJNLjhtaRZsIDptVDiL9LyF/
    pW3Ubct5VoTmXQwHowAkRTFHA9MMHfVRDrQNgxN1x69SEg3A539yYd4DnkpXZQxJ
    TbyfxxscET/ZmprWT3rwJV5JFHs9In4sQYCBW0YdzRFgCR35cWICPU+SILSsQnqc
    IVvCcq5EAtRvVbPEnnGKeRC15CPOQwIf6eaiqcrL5uQVwGyN1LmoZRuUIsxHXeQV
    NL8gnqIkJasd6pkVPXo+WQxlCGhvuv/bcsd25mLm2GRKv7xpgxvcHW+GxuVQKjsC
    AwEAAaNTMFEwHQYDVR0OBBYEFIp52wHhXQmQnJ7yf5xabuRafdFcMB8GA1UdIwQY
    MBaAFIp52wHhXQmQnJ7yf5xabuRafdFcMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
    hvcNAQELBQADggIBANJRltTMSRPVwLs6EsyXd3uEI6ekTT7IA47/Rl+lwflHcyJk
    uZigcaVluNdmy+/+8oTmyyOt2ZcaidJGMW+DGuWmP21iq++vGEcsvKBafugZPtb/
    WrxReltHrZB36SvGNB3mvn2iJdzdgDjz3gYolhO5T9pC/ZIU5kiEc+T6Px7Dmz8D
    wcMHGY4iPgA5XyWQ4B7iQTc3OTU55CqRl3Sy//bH+qnIQRs+dq+ExeVKJVKt2Eq+
    pO1TdFKTHDnVApw86jws6sF/3+WN/6lHfkmLHVWPxmJTD2tkbTm/iekoV21hZXHh
    b6BJTeyfLhSpMyfP6qRDyyrBA5/LVwLjq3eS+mw5BDzT+A2s6dyIVTAHXtyJrNXL
    i/rSPXjRTZxS3qv5swQQKdyNbCe7eK9TZ79pcwyPPBtKkpwgsfbaOhs58WzdW8G7
    o2VxqwBruh7mcauer501S0I9I07X3tgysJp59YfpAtHg0NlYe3hR0EhUdgkSw84p
    18ydRojTutY88EjU/cax5vh12Qf7NBUt5Rxg9LFxgmh+stmhy7NPZqEYLwm5efL0
    OWmIwWm9Vjrg5lNVTdt7T+wwmVT8xQhSdaNzaeSocGRNdgvZs7r8ctHC7y+Ru3Bw
    uiRjr1W5YJPKXaGAR+D4fPFGm1xgmqFUQa3FB+kIKlNhnLKiGTMPY8M4J8ZD
    -----END CERTIFICATE-----
  edge.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEPzCCAicCFHd3lSYZmjIkMpWmPPVE+0mA94Z4MA0GCSqGSIb3DQEBCwUAMFwx
    CzAJBgNVBAYTAkNOMREwDwYDVQQIDAhaaGVqaWFuZzERMA8GA1UEBwwISGFuZ3po
    b3UxETAPBgNVBAoMCEt1YmVFZGdlMRQwEgYDVQQDDAtrdWJlZWRnZS5pbzAeFw0y
    MTA2MTgxNDM4MDhaFw0yMjA2MTgxNDM4MDhaMFwxCzAJBgNVBAYTAkNOMREwDwYD
    VQQIDAhaaGVqaWFuZzERMA8GA1UEBwwISGFuZ3pob3UxETAPBgNVBAoMCEt1YmVF
    ZGdlMRQwEgYDVQQDDAtrdWJlZWRnZS5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAK5pL+FJTdSJWwmduQ6wRkHgUoHhvwiTG5qxn6oWaF016WqG1Lpw
    RE269pfYBNQPFrJL2cfJ2OB7ZD3BNTlkHtELvRVn8r5H5Y3NUqUYs2tW6bqwS5Qj
    IZ65wNDoighsfEruzKwDeJbW8Gnkt47BXlN243bEDQ8nYl475CAIHKZ+UZLQDUId
    wkDWQyZVSa0yppSnupylqUIsxleN0frChFETGEE2nmGiw/pMPhYv7wOzrlSN+RRt
    8lyzYNtDYhOG5rioBPpiM0Y21XgPEhlht7hJRidGWqPMskBLpWCWO2ldqSdQfwqa
    qfrWWr79Wpm4NiAdIftI8IAAtt/SnaERwGcCAwEAATANBgkqhkiG9w0BAQsFAAOC
    AgEAQuX2Jal1aPRZKrI4HeOPmz4ipEuibxA17QkpYgoQL633fQZvbLE0B/GSvf+5
    NW8fZBWvuK9f4CviR18CAb51EmBAa1wfEAaLgSEWsZFpx1F5p2BfCnTrEOl/NKrL
    qNZ7Ns3tqzKS8G8aDGqyhRADbJ25eKGa/QfnXAXAFXNxu+EtMmw5si/x57nv+79W
    YMUbC/9Aqw9Azw9BiIW0oPEODrTeEjpR/7MCLdnn6wmtDOyKaQ+08Q2GNq6/on6G
    IP7A8/9cImmIT6dtKE9aldJUDe5mOrt9UfW57YU7+g/KnRGs1aL2+gpzpEZFqs9D
    CYHYDu392/cMBQaKOp3dOQJVWsBsxzcZglzWDpLu+pwWqgpGST/rmPmELsvb5e1N
    oHL2Fv/Bw7gkcyl5UPcjekvjuionnBIjFtN7VVsPzsuekFE1hTnbFZGjQutfiGGi
    mQ0RJxu6bxAoYkAsob+nw9DmHdQmAO57t8lKPzPFk5WGyJJD+m1of7lq877mt+9K
    HRp5iyvwwjYjLuHJ865C04TEhmWvf1nEpa4y6IaxXHQQAwVIdH5XaRJOedfEEWGJ
    KwhrcQltvMflHM6AKHcHaBUU2+XgfZcKjRrMcSmMKU3v5GYpBqINosD4l97avvdL
    K1kvQ/l6rOku9ftoq6q8nraUPdHRbpPr15BvjwXeL/87LBM=
    -----END CERTIFICATE-----
  edge.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEArmkv4UlN1IlbCZ25DrBGQeBSgeG/CJMbmrGfqhZoXTXpaobU
    unBETbr2l9gE1A8WskvZx8nY4HtkPcE1OWQe0Qu9FWfyvkfljc1SpRiza1bpurBL
    lCMhnrnA0OiKCGx8Su7MrAN4ltbwaeS3jsFeU3bjdsQNDydiXjvkIAgcpn5RktAN
    Qh3CQNZDJlVJrTKmlKe6nKWpQizGV43R+sKEURMYQTaeYaLD+kw+Fi/vA7OuVI35
    FG3yXLNg20NiE4bmuKgE+mIzRjbVeA8SGWG3uElGJ0Zao8yyQEulYJY7aV2pJ1B/
    Cpqp+tZavv1ambg2IB0h+0jwgAC239KdoRHAZwIDAQABAoIBAQCTqZ7OAEAS14/q
    Hk0VcIyrLX7tU/FnExVl7UieuoX1lLVgaXMlvfM2VDp+6Hd+CqBOqAVkLzKdLBr8
    Zd3oDypAFs4pl25fR4PEgLed68HL+TO9yZDThMLsHZxvwtFKvH6m+nLyl6W7H5NA
    NFJsXK69v4RpgycDU3bnDZHgxL1s/1KDFSmh2EA0Xy1dZWCn9xUOZOs6zCOiyff+
    3QZBHltnosossVgBIG5Gf4h+57vfhbQ0J7PKj1AUnJQQkoOJ7j3NCXM0NX5bnmkv
    0A9shWtIQW429ti9k7FqMxWXhygV/5hsFXpT6YtVKxQW7DTCgllogEDae9aorJMc
    injuh6kxAoGBAOXgPr1ZcbIVeP/Qfsl9yD+wo+Jjm7gtqudjcURHUh+1exkpQE48
    Uojz6JDdqjmI/gQ0hStsIb+Dj41M/YNi3bkWFOW3Qgti92ZllsYIzK0YwsHtFFUE
    xJyVW6UpdkBkWv0YyAP0suo+OKEDANwngbawevObVIZZgn0yJIXqyGI7AoGBAMI7
    TZHC4sXpkyAezSTMbtE0KAvJpY/5asLxsHA33rvRQqIcJPuZynFqxtvpAeYhY4zB
    Jdx1CvA8HvEf77iPTeQthtIYAIVpvF8Im+/9VGKLdiKr/BQ8V0VbMNDuNu5mchVo
    wrbICzRoG7jSHzDk/UJ5lRcZexEqrTtATsr69uvFAoGAMEc8ZgAXBNPFqdRcDG1C
    VT3/7VgGKFRPBHG6JCDmeope5BXpz4STwPeY7HPhgFvpHXD6VvhKzjIPQBnfVGy7
    LFga43Pthv6t/u9vDwBiHCiLHrdwAbsSn+Aucy2WDEgHZAiEWXBW8yNGOWqsD5Cs
    iXXfHLKOufiqkyioywdYNmkCgYBJK7AYNlPZ/RlI43Gi6ETjGQPxFOEDMRHwKL6w
    N8v382hny7R++DvUqEYL+GaXvIJVNzo9J/ab8/owGjjjzVCpoiEFKrefiurE3mho
    a4YLrcAuZZ4MPYMfBLCKNQOKohteR137H7dg4ct3v+iyMcHa9hSdZCMBn5MtHBfS
    zeKRhQKBgAuhiSdDfU1DZnzHrsfW7CQMzgOLQOfpR/WHqVlx24nWDqZsk47ufeEE
    wndSWOWXtzs8AhHtGC+J4wwB2LjkTWyYVIoYADeDm/7Ru0PBaq3S766Ge8tEJRAv
    YgrDrX1dgvVpe4DsJosjximI92KyvvfGWqRVAhgu0+hs02eMD1/8
    -----END RSA PRIVATE KEY-----

