apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: 10000
    name: cloudhub
  - port: 10001
    name: quic
  - port: 10002
    name: certhttp
  - port: 9443
    name: router
  - port: 443
    name: https
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: NodePort
